name: UHC
version: 0.2
author: DeanX
main: me.deanx.uhc.Plugin
description: UHC plugin
api-version: 1.13

commands:
  UHC:
    description: UHC command
  center:
    description: Get the distance to center
    permission: uhc.center
    aliases: centerdistance
