name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
      - name: Push release
        run: |
          git init
          git config --local user.name "github-actions"
          git config --local user.email "41898282+github-actions@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "Publish Release"
          git remote add origin "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}"
          git push -f -u origin release
        working-directory: build/libs


  minecraft-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release
          path: plugins
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download PaperUpdater
        uses: robinraju/release-downloader@v1.4
        with:
          repository: XZTDean/PaperUpdater
          latest: true
          fileName: "PaperUpdater*.jar"
      - name: Download minecraft new build
        run: java -jar -Xms4G -Xmx4G PaperUpdater*.jar
      - name: Cache needed plugins
        id: cache-plugins
        uses: actions/cache@v3
        with:
          path: plugins/StopServer.jar
          key: ${{ runner.os }}-cache-plugins-StopServer.jar
      - name: Download needed plugins
        if: steps.cache-plugins.outputs.cache-hit != 'true'
        run: wget -q https://dl.isurl.tech/StopServer.jar
        working-directory: plugins
      - name: Agree eula
        run: echo "eula=true" > eula.txt
      - name: Run the game
        run: java -Xms6G -Xmx6G -jar paper.jar --nogui
      - name: Check error in logs
        run: grep "Could not load 'plugins" logs/latest.log || grep "Error occurred while enabling UHC" logs/latest.log && exit 1
